export const menuLinks = [
  {
    name: '社團歷史',
    url: '/history',
  },
  {
    name: '社友來稿',
    url: '/posts',
  },
  {
    name: '留言板',
    url: '/chat',
  },
  {
    name: '贊助我們',
    url: '/sponser',
  },
]

export const clubLinks = [
  {
    title: '國立清華大學天文社 NTHU Astronomy Club (官網)',
    url: 'http://my.nthu.edu.tw/~res9202/',
    image: '/img/icons/globe@4x.png',
  },
  {
    title: '清大天文社 NTHU Astronomy Club (Facebook)',
    url: 'https://www.facebook.com/nthuastro',
    image: '/img/icons/facebook@4x.png',
  },
  {
    title: '清大天文社 NTHU Astronomy Club (Instagram)',
    url: 'https://www.instagram.com/nthuastroclub/',
    image: '/img/icons/instagram@4x.png',
  },
]

export const relatedLinks = [
  {
    title: '清大天文社四十周年',
    url: 'https://sites.google.com/site/nthuastro40th/',
    image: '/img/icons/cake@4x.png',
  },
  {
    title: '2021 清華大學星空之子天文營',
    url: 'http://my.nthu.edu.tw/~res9202/astrocamp/2021/',
    image: '/img/icons/library@4x.png',
  },
  {
    title: '清華大學天文台',
    url: 'http://nthuobs.phys.nthu.edu.tw/tw',
    image: '/img/icons/planetarium@4x.png',
  },
  {
    title: '全國大學天文社聯盟 (Facebook)',
    url: 'https://www.facebook.com/AstronomyClubUnion/',
    image: '/img/icons/school@4x.png',
  },
]

export const CABINETS = [
  {
    age: 0,
    name: '創社元老',
    positions: [
      { name: '徐魁森', department: '物理 71', position: '創社元老' },
      { name: '沈采蘋', department: '物理 74', position: '創社元老' },
      { name: '陳昱寧', department: '物理 74', position: '創社元老' },
      { name: '葉迎春', department: '物理 74', position: '創社元老' },
      { name: '鄧延璋', department: '物理 74', position: '創社元老' },
    ],
  },
  {
    age: 1,
    name: '第1屆',
    positions: [{ name: '鄧延璋', department: '物理 74', position: '社長' }],
  },
  {
    age: 2,
    name: '第2屆',
    positions: [{ name: '葉則亮', department: '核工 75', position: '社長' }],
  },
  {
    age: 3,
    name: '第3屆',
    positions: [{ name: '楊錫欽', department: '化學 75', position: '社長' }],
  },
  {
    age: 4,
    name: '第4屆',
    positions: [{ name: '黃一農', department: '物理 77', position: '社長' }],
  },
  {
    age: 5,
    name: '第5屆',
    positions: [{ name: '吳覺宇', department: '物理 77', position: '社長' }],
  },
  {
    age: 6,
    name: '第6屆',
    positions: [{ name: '江啟文', department: '物理 78', position: '社長' }],
  },
  {
    age: 7,
    name: '第7屆',
    positions: [{ name: '陳　偉', department: '物理 80', position: '社長' }],
  },
  {
    age: 8,
    name: '第8屆',
    positions: [
      { name: '許哲榮', department: '物理 80', position: '社長' },
      { name: '謝立宜', department: '物理 81', position: '副社長' },
      { name: '謝立宜', department: '物理 81', position: '儀器股' },
      { name: '陳俊良', department: '物理 81', position: '總務股' },
    ],
  },
  {
    age: 9,
    name: '第9屆',
    positions: [
      { name: '謝立宜', department: '物理 81', position: '社長' },
      { name: '陳劍琴', department: '物理 82', position: '副社長' },
      { name: '謝立宜', department: '物理 81', position: '儀器股' },
      { name: '謝行宜', department: '物理 81', position: '儀器股' },
      { name: '劉壽華', department: '物理 81', position: '學術股' },
      { name: '李世林', department: '物理 83', position: '學術股' },
      { name: '張家彧', department: '核工 83', position: '攝影股' },
      { name: '傅柏叡', department: '工工 83', position: '攝影股' },
      { name: '王理平', department: '物理 83', position: '宣傳股' },
      { name: '吳美樺', department: '物理 83', position: '社史股' },
    ],
  },
  {
    age: 10,
    name: '第10屆',
    positions: [
      { name: '傅柏叡', department: '工工 83', position: '社長' },
      { name: '吳美樺', department: '物理 83', position: '副社長' },
      { name: '李世林', department: '物理 83', position: '儀器股' },
      { name: '張家彧', department: '核工 83', position: '攝影股' },
      { name: '林正琪', department: '物理 83', position: '觀星股' },
      { name: '柯源崑', department: '物理 83', position: '總務股' },
      { name: '王理平', department: '物理 83', position: '宣傳股' },
      { name: '徐曉陽', department: '物理 83', position: '社史股' },
    ],
  },
  {
    age: 11,
    name: '第11屆',
    positions: [
      { name: '黃陸霆', department: '核工 84', position: '社長' },
      { name: '鍾郁芸', department: '物理 84', position: '副社長' },
      { name: '張　靜', department: '核工 84', position: '資料股' },
      { name: '魏裕益', department: '工工 84', position: '儀器股' },
      { name: '劉安國', department: '電機 84', position: '學術股' },
      { name: '張景新', department: '化學 84', position: '攝影股' },
      { name: '陳明興', department: '核工 84', position: '總務股' },
      { name: '鍾郁芸', department: '物理 84', position: '康樂' },
      { name: '高嘉宏', department: '物理 84', position: '聯絡股' },
    ],
  },
  {
    age: 12,
    name: '第12屆',
    positions: [
      { name: '魏裕益', department: '工工 84', position: '社長' },
      { name: '李梅華', department: '物理 85', position: '副社長' },
      { name: '廖乃慧', department: '核工 85', position: '資料股' },
      { name: '林志保', department: '核工 85', position: '資料股' },
      { name: '溫兆均', department: '電機 85', position: '儀器股' },
      { name: '李河新', department: '物理 85', position: '學術股' },
      { name: '施學圭', department: '材料 85', position: '觀測股' },
      { name: '李岱穎', department: '動機 85', position: '觀測股' },
      { name: '張育仁', department: '物理 84', position: '觀星股' },
      { name: '李燦榮', department: '物理 85', position: '活動股' },
      { name: '張慧玉', department: '電機 85', position: '圖書股' },
      { name: '鍾郁芸', department: '物理 84', position: '總務股' },
      { name: '曹中亞', department: '核工 85', position: '宣傳股' },
      { name: '羅宗仁', department: '物理 85', position: '聯絡股' },
    ],
  },
  {
    age: 13,
    name: '第13屆',
    positions: [
      { name: '林富源', department: '物理 86', position: '社長' },
      { name: '金升光', department: '物理 86', position: '資料股' },
      { name: '李訓德', department: '物理 86', position: '資料股' },
      { name: '鄭新達', department: '數學 86', position: '學術股' },
      { name: '黃正得', department: '核工 86', position: '觀測股' },
      { name: '張思晉', department: '物理 86', position: '觀測股' },
      { name: '謝璧妃', department: '電機 86', position: '觀測股' },
      { name: '陳明傑', department: '化學 86', position: '攝影股' },
      { name: '馮德如', department: '物理 86', position: '活動股' },
      { name: '王環苓', department: '化工 86', position: '圖書股' },
      { name: '王敏惠', department: '物理 86', position: '總務股' },
      { name: '周炳榮', department: '物理 86', position: '聯絡股' },
    ],
  },
  {
    age: 14,
    name: '第14屆',
    positions: [
      { name: '張祥光', department: '物理 87', position: '社長' },
      { name: '王莓瑜', department: '核工 87', position: '副社長' },
      { name: '黃清儀', department: '化學 87', position: '設備股' },
      { name: '劉水苔', department: '核工 87', position: '觀星股' },
      { name: '馮智聰', department: '化學 87', position: '觀星股' },
      { name: '王智立', department: '物理 87', position: '活動股' },
      { name: '陳少棠', department: '物理 87', position: '文書' },
      { name: '余樂山', department: '物理 87', position: '圖書股' },
      { name: '陳金燦', department: '物理 87', position: '總務股' },
      { name: '李嘉明', department: '物理 87', position: '聯絡股' },
      { name: '洪絹欲', department: '材料 87', position: '進修股' },
      { name: '徐瑞龍', department: '材料 87', position: '進修股' },
    ],
  },
  {
    age: 15,
    name: '第15屆',
    positions: [
      { name: '張　瑋', department: '材料 88', position: '社長' },
      { name: '王章琪', department: '物理 88', position: '副社長' },
      { name: '許櫻齡', department: '經濟 88', position: '資料股' },
      { name: '周　翊', department: '物理 88', position: '學術股' },
      { name: '范震宇', department: '物理 88', position: '設備股' },
      { name: '黃敏瑞', department: '物理 88', position: '攝影股' },
      { name: '柯光武', department: '材料 88', position: '觀星股' },
      { name: '洪仁勝', department: '電機 88', position: '活動股' },
      { name: '陳正華', department: '物理 88', position: '圖書股' },
      { name: '文克勤', department: '動機 88', position: '總務股' },
    ],
  },
  {
    age: 16,
    name: '第16屆',
    positions: [
      { name: '宋皇志', department: '物理 89', position: '社長' },
      { name: '蘇裕農', department: '化學 89', position: '資料股' },
      { name: '余慧怜', department: '經濟 89', position: '資料股' },
      { name: '陳俊哲', department: '物理 89', position: '設備股' },
      { name: '劉大勇', department: '物理 89', position: '攝影股' },
      { name: '陳建邦', department: '化學 89', position: '活動股' },
      { name: '王章琪', department: '物理 88', position: '圖書股' },
      { name: '劉樹勳', department: '物理 89', position: '總務股' },
      { name: '劉振立', department: '材料 89', position: '公關股' },
      { name: '黃莉娥', department: '經濟 89', position: '宣傳股' },
    ],
  },
  {
    age: 17,
    name: '第17屆',
    positions: [{ name: '金升光', department: '物理 86', position: '社長' }],
  },
  {
    age: 18,
    name: '第18屆',
    positions: [{ name: '許家銘', department: '物理 90', position: '社長' }],
  },
  {
    age: 19,
    name: '第19屆',
    positions: [{ name: '朱恩立', department: '物理 91', position: '社長' }],
  },
  {
    age: 20,
    name: '第20屆',
    positions: [{ name: '鄭宏文', department: '物理 93', position: '社長' }],
  },
  {
    age: 21,
    name: '第21屆',
    positions: [
      { name: '賴詩萍', department: '物理 93', position: '社長' },
      { name: '金振山', department: '物理 94', position: '副社長' },
      { name: '涂圓欣', department: '外語 94', position: '美宣股' },
    ],
  },
  {
    age: 22,
    name: '第22屆',
    positions: [{ name: '金振山', department: '物理 94', position: '社長' }],
  },
  {
    age: 23,
    name: '第23屆',
    positions: [{ name: '徐永源', department: '物理 95', position: '社長' }],
  },
  {
    age: 24,
    name: '第24屆',
    positions: [{ name: '林士杰', department: '生科 96', position: '社長' }],
  },
  {
    age: 25,
    name: '第25屆',
    positions: [{ name: '涂宗憲', department: '電機 97', position: '社長' }],
  },
  {
    age: 26,
    name: '第26屆',
    positions: [
      { name: '鄭　莊', department: '電機 00', position: '社長' },
      { name: '吳承恩', department: '物理 98', position: '社長' },
      { name: '吳承恩', department: '物理 98', position: '副社長' },
      { name: '林柏全', department: '電機 99', position: '活動股' },
      { name: '林柏全', department: '電機 99', position: '美宣股' },
      { name: '涂宗憲', department: '電機 97', position: '器材股' },
    ],
  },
  {
    age: 27,
    name: '第27屆',
    positions: [{ name: '杜敏誠', department: '工科 99', position: '社長' }],
  },
  {
    age: 28,
    name: '第28屆',
    positions: [
      { name: '陳　鎧', department: '物理 01', position: '社長' },
      { name: '徐如萱', department: '外語 01', position: '副社長' },
      { name: '鄭雅駿', department: '物理 01', position: '星子BBS站長' },
    ],
  },
  {
    age: 29,
    name: '第29屆',
    positions: [{ name: '陳　鎧', department: '物理 01', position: '社長' }],
  },
  {
    age: 30,
    name: '第30屆',
    positions: [
      { name: '楊欲忠', department: '物理 02', position: '社長' },
      { name: '胡佳伶', department: '生科 03', position: '教學' },
      { name: '丘政倫', department: '物理 03', position: '活動' },
      { name: '莊韻絹', department: '', position: '美宣' },
      { name: '王怡喬', department: '物理 03', position: '生器' },
    ],
  },
  {
    age: 31,
    name: '第31屆',
    positions: [
      { name: '丘政倫', department: '物理 03', position: '社長' },
      { name: '王怡喬', department: '物理 03', position: '副社長' },
      { name: '潘國全', department: '物理 04', position: '器材' },
      { name: '李毓庭', department: '物理 04', position: '教學' },
      { name: '王立涵', department: '工科 04', position: '文資' },
      { name: '徐雅玲', department: '物理 04', position: '美宣' },
    ],
  },
  {
    age: 32,
    name: '第32屆',
    positions: [
      { name: '潘國全', department: '物理 04', position: '社長' },
      {
        name: '潘國全',
        department: '物理 04',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 33,
    name: '第33屆',
    positions: [{ name: '陳倬思', department: '物理 05', position: '社長' }],
  },
  {
    age: 34,
    name: '第34屆',
    positions: [
      { name: '王立涵', department: '工科 04', position: '社長' },
      { name: '陳依婷', department: '物理 07', position: '副社長' },
    ],
  },
  {
    age: 35,
    name: '第35屆',
    positions: [
      { name: '陳依婷', department: '物理 07', position: '社長' },
      { name: '廖唯誠', department: '電機 08', position: '副社長' },
    ],
  },
  {
    age: 36,
    name: '第36屆',
    positions: [
      { name: '廖唯誠', department: '電機 08', position: '社長' },
      { name: '王嘉瑋', department: '物理 09', position: '器材' },
      { name: '何明諠', department: '電機 09', position: '活動' },
      { name: '廖官榆', department: '電機 08', position: '總務' },
      {
        name: '洪群佾',
        department: '電機 08',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 37,
    name: '第37屆',
    positions: [
      { name: '何明諠', department: '電機 09', position: '社長' },
      { name: '林大為', department: '理雙 10', position: '副社長' },
      { name: '王嘉瑋', department: '物理 09', position: '副社長' },
      { name: '林大為', department: '理雙 10', position: '器材' },
      { name: '張浩偉', department: '化學 10', position: '教學' },
      { name: '李昀翰', department: '資工 10', position: '文資' },
      { name: '黃柏榮', department: '化學 10', position: '美宣' },
      {
        name: '張浩偉',
        department: '化學 10',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 38,
    name: '第38屆',
    positions: [
      { name: '黃柏榮', department: '化學 10', position: '社長' },
      { name: '張文軒', department: '物理 11', position: '儀器' },
      { name: '張雅惠', department: '理雙 11', position: '教學' },
      { name: '林雨德', department: '化學 11', position: '活動' },
      { name: '吳乃君', department: '人社 11', position: '總務' },
      { name: '吳乃君', department: '人社 11', position: '美宣' },
      {
        name: '張浩偉',
        department: '化學 10',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 39,
    name: '第39屆',
    positions: [
      { name: '張文軒', department: '物理 11', position: '社長' },
      { name: '林聖鈞', department: '數學 12', position: '儀器' },
      { name: '謝爾庭', department: '材料 12', position: '教學' },
      { name: '馮培瑄', department: '材料 12', position: '活動' },
      { name: '林雨德', department: '化學 11', position: '生活' },
      { name: '楊晴棻', department: '生科 12', position: '總務' },
      {
        name: '林聖鈞',
        department: '數學 12',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 40,
    name: '第40屆',
    positions: [
      { name: '林聖鈞', department: '數學 12', position: '社長' },
      { name: '謝爾庭', department: '材料 12', position: '副社長' },
      { name: '王澄宇', department: '物理 13', position: '儀器' },
      { name: '劉彥廷', department: '動機 13', position: '儀器' },
      { name: '廖又賢', department: '物理 13', position: '教學' },
      { name: '簡若帆', department: '物理 13', position: '生活' },
      { name: '徐晨桓', department: '物理 13', position: '生活' },
      { name: '簡若帆', department: '物理 13', position: '總務' },
      { name: '王澄宇', department: '物理 13', position: '攝影' },
      {
        name: '郭威廷',
        department: '物理 13',
        position: '竹女天文社師',
      },
      {
        name: '簡若帆',
        department: '物理 13',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 41,
    name: '第41屆',
    positions: [
      { name: '簡若帆', department: '物理 13', position: '社長' },
      { name: '徐晨桓', department: '物理 13', position: '副社長' },
      { name: '吳岳明', department: '電機 14', position: '儀器' },
      { name: '陳二中', department: '物理 14', position: '儀器' },
      { name: '陳可璇', department: '材料 14', position: '儀器' },
      { name: '劉晉翰', department: '交大電機 103', position: '教學' },
      { name: '張欽堯', department: '醫科14', position: '活動' },
      { name: '詹凱勳', department: '物理 14', position: '生活' },
      { name: '林宛瑩', department: '動機 14', position: '生活' },
      { name: '姚玥華', department: '動機 13', position: '生活' },
      { name: '許智鈞', department: '工院 14', position: '網管' },
      { name: '楊雅菉', department: '物理 14', position: '總務' },
      {
        name: '吳岳明',
        department: '電機 14',
        position: '竹女天文社師',
      },
      {
        name: '詹凱勳',
        department: '物理 14',
        position: '竹中天文社師',
      },
    ],
  },
  {
    age: 42,
    name: '第42屆',
    positions: [
      { name: '陳可璇', department: '材料 14', position: '社長' },
      { name: '詹凱勳', department: '物理 14', position: '副社長' },
      { name: '林宛瑩', department: '動機 14', position: '副社長' },
      { name: '李沅達', department: '物理 15', position: '儀器' },
      { name: '葉士維', department: '動機 15', position: '儀器' },
      { name: '沈勇賢', department: '物理 15', position: '教學' },
      { name: '鄭峻騰', department: '物理 15', position: '活動' },
      { name: '葉翰文', department: '物理 15', position: '生活' },
      { name: '卓苑婷', department: '醫環  15', position: '生活' },
      { name: '劉　靜', department: '材料 15', position: '網管' },
      { name: '林彥彤', department: '動機 14', position: '網管' },
      { name: '鍾沂倫', department: '物理 15', position: '總務' },
    ],
  },
  {
    age: 43,
    name: '第43屆',
    positions: [
      { name: '鍾沂倫', department: '物理 15', position: '社長' },
      { name: '葉翰文', department: '物理 15', position: '副社長' },
      { name: '劉　靜', department: '材料 15', position: '副社長' },
      { name: '葉士維', department: '動機 15', position: '副社長' },
      { name: '劉明威', department: '物理 16', position: '儀器' },
      { name: '施子庭', department: '工工 16', position: '儀器' },
      { name: '吳冠昱', department: '材料 16', position: '儀器' },
      { name: '簡士傑', department: '材料 16', position: '教學' },
      { name: '丁聿懷', department: '物理 16', position: '生活' },
      { name: '洪嘉謙', department: '計財 16', position: '生活' },
      { name: '劉欣蓉', department: '人社 16', position: '生活' },
      { name: '吳紹銘', department: '物理 16', position: '網管' },
      { name: '簡士傑', department: '材料 16', position: '總務' },
    ],
  },
  {
    age: 44,
    name: '第44屆',
    positions: [
      { name: '吳冠昱', department: '材料 16', position: '社長' },
      { name: '簡士傑', department: '材料 16', position: '副社長' },
      { name: '洪嘉謙', department: '計財 16', position: '副社長' },
      { name: '施子庭', department: '工工 16', position: '副社長' },
      { name: '梁閎翔', department: '電機 17', position: '儀器' },
      { name: '黃聖文', department: '物理 17', position: '儀器' },
      { name: '呂鈞恩', department: '物理 17', position: '儀器' },
      { name: '許皓甯', department: '外語 17', position: '儀器' },
      { name: '蘇哲廣', department: '物理 17', position: '教學' },
      { name: '梁嘉君', department: '物理 17', position: '生活' },
      { name: '何明倩', department: '工科 17', position: '生活' },
      { name: '林方婷', department: '動機 17', position: '網管' },
      { name: '陳郁閔', department: '化工 17', position: '網管' },
      { name: '洪嘉謙', department: '計財 16', position: '服學助教' },
      { name: '施子庭', department: '工工 16', position: '服學助教' },
    ],
  },
  {
    age: 45,
    name: '第45屆',
    positions: [
      { name: '梁閎翔', department: '電機 17', position: '社長' },
      { name: '呂鈞恩', department: '物理 17', position: '副社長' },
      { name: '何明倩', department: '工科 17', position: '副社長' },
      { name: '繆鎬宇', department: '交大資工 107', position: '儀器' },
      { name: '徐安廷', department: '電機 18', position: '儀器' },
      { name: '郭人萱', department: '外語 18', position: '儀器' },
      { name: '呂心禾', department: '電機 18', position: '教學' },
      { name: '林宏修', department: '物理 18', position: '教學' },
      { name: '吳玫茜', department: '理雙 18', position: '生活' },
      { name: '邱羿櫳', department: '物理 18', position: '網管' },
      { name: '張長霖', department: '電機 18', position: '總務' },
      { name: '游芳綾', department: '經濟 18', position: '服學助教' },
      { name: '邱羿櫳', department: '物理 18', position: '服學助教' },
      {
        name: '吳冠昱',
        department: '材料 16',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 46,
    name: '第46屆',
    positions: [
      { name: '徐安廷', department: '電機 18', position: '社長' },
      { name: '郭人萱', department: '外語 18', position: '副社長' },
      { name: '邱羿櫳', department: '物理 18', position: '副社長' },
      { name: '黃志強', department: '交大電機 108', position: '儀器' },
      { name: '林禹辰', department: '醫環 19', position: '儀器' },
      { name: '黃昱修', department: '電機 19', position: '教學' },
      { name: '林新綠', department: '人社 19', position: '教學' },
      { name: '杜政諺', department: '電機 19', position: '生活' },
      { name: '鄭冠群', department: '工科 19', position: '生活' },
      { name: '張智維', department: '動機 19', position: '網管' },
      { name: '方擷淅', department: '醫環 19', position: '總務' },
      { name: '胡琬欣', department: '材料 19', position: '服學助教' },
      {
        name: '吳冠昱',
        department: '材料 16',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 47,
    name: '第47屆',
    positions: [
      { name: '黃昱修', department: '電機 19', position: '社長' },
      { name: '林新綠', department: '人社 19', position: '副社長' },
      { name: '林禹辰', department: '醫環 19', position: '副社長' },
      { name: '李孟憬', department: '電機 20', position: '儀器' },
      { name: '盧顗文', department: '數學 20', position: '儀器' },
      { name: '陳子婷', department: '外語 20', position: '教學' },
      { name: '林舜民', department: '醫環 20', position: '教學' },
      { name: '張佐渝', department: '醫環 20', position: '生活' },
      { name: '賴思縈', department: '醫環 20', position: '生活' },
      { name: '林宥彤', department: '醫環 20', position: '總務' },
      { name: '張傳佳', department: '電機 20', position: '服學助教' },
      { name: '陳禹豪', department: '電機 20', position: '服學助教' },
    ],
  },
  {
    age: 48,
    name: '第48屆',
    positions: [
      { name: '陳子婷', department: '外語 20', position: '社長' },
      { name: '李孟憬', department: '電機 20', position: '副社長' },
      { name: '林宥彤', department: '醫環 20', position: '副社長' },
      { name: '吳柏叡', department: '數學 21', position: '儀器' },
      { name: '王立宇', department: '工科 21', position: '儀器' },
      { name: '林彥興', department: '理雙 21', position: '教學' },
      { name: '李丞恩', department: '電機 21', position: '教學' },
      { name: '蘇彥碩', department: '數學 21', position: '生活' },
      { name: '劉文穎', department: '生科 21', position: '生活' },
      { name: '陳姿妤', department: '中文 21', position: '網管' },
      { name: '王碩傑', department: '動機 21', position: '總務' },
    ],
  },
  {
    age: 49,
    name: '第49屆',
    positions: [
      { name: '王立宇', department: '工科 21', position: '社長' },
      { name: '林彥興', department: '理雙 21', position: '副社長' },
      { name: '蘇彥碩', department: '數學 21', position: '副社長' },
      { name: '張侑勛', department: '工科 22', position: '儀器' },
      { name: '吳家頡', department: '教育學院學士班 22', position: '儀器' },
      { name: '張瓊尹', department: '工科 22', position: '教學' },
      { name: '羅晨昀', department: '外語 22', position: '教學' },
      { name: '謝長佑', department: '數學 22', position: '生活' },
      { name: '羅子翔', department: '數學 22', position: '生活' },
      { name: '傅　喻', department: '人社 22', position: '總務' },
      { name: '吳家頡', department: '教育學院學士班 22', position: '服學助教' },
      { name: '張瓊尹', department: '工科 22', position: '服學助教' },
      {
        name: '林彥興',
        department: '理雙 21',
        position: '竹女天文社師',
      },
    ],
  },
  {
    age: 50,
    name: '第50屆',
    positions: [
      { name: '傅　喻', department: '人社 22', position: '社長' },
      { name: '張宸勻', department: '物理 23', position: '儀器' },
      { name: '李經玄', department: '工科 23', position: '儀器' },
      { name: '林上景', department: '物理 23', position: '教學' },
      { name: '葉勇陞', department: '物理 23', position: '教學' },
      { name: '許正憲', department: '物理 23', position: '教學' },
      { name: '吳奕勳', department: '經濟 23', position: '教學' },
      { name: '連思瑜', department: '人社 23', position: '活動' },
      { name: '蔡皓崴', department: '工科 23', position: '生活' },
      { name: '劉翔緯', department: '工科 23', position: '生活' },
      { name: '謝明學', department: '物理 23', position: '生活' },
      { name: '董承霈', department: '不分系 23', position: '生活' },
      { name: '吳奕勳', department: '經濟 23', position: '總務' },
      { name: '廖韋涵', department: '人社 23', position: '文書' },
    ],
  },
  {
    age: 51,
    name: '第51屆',
    positions: [
      { name: '林上景', department: '物理 23', position: '社長' },
      { name: '吳奕勳', department: '經濟 23', position: '副社長' },
      { name: '劉翔緯', department: '工科 23', position: '副社長' },
      { name: '侯皓予', department: '資工 24', position: '儀器' },
      { name: '李駿毅', department: '原科 24', position: '儀器' },
      { name: '劉祐辰', department: '動機 24', position: '儀器' },
      { name: '標冠廷', department: '化學 24', position: '儀器' },
      { name: '曾詠暄', department: '工科 24', position: '教學' },
      { name: '蒲思云', department: '物理 24', position: '教學' },
      { name: '葉奉明', department: '材料 24', position: '教學' },
      { name: '江宇謙', department: '工院 24', position: '生活' },
      { name: '黃巧兒', department: '藝設 24', position: '生活' },
      { name: '邱儀恩', department: '藝設 24', position: '生活' },
      { name: '謝明翰', department: '電機 23', position: '生活' },
      { name: '何梓華', department: '物理 24', position: '網管' },
      { name: '柯宇珊', department: '不分系 24', position: '總務' },
    ],
  },
]
